service: product-service

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: eu-west-1
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}

functions:
  products:
    handler: handler.products
    events:
      - http:
          path: products
          method: get
          cors: true

  product:
    handler: handler-product.product
    events:
      - http:
          path: products/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  addProduct:
    handler: handler-add-product.addProduct
    events:
      - http:
          path: /products
          method: post
          cors: true
