service: import-file-aws-node
frameworkVersion: '2'
configValidationMode: error


provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: '20201221'

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::import-file-aws-node"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::import-file-aws-node/*"

functions:
  importProductsFileDev:
    handler: handler-products-file.importProductsFileDev
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParserDev:
    handler: handler-file-parser.importFileParserDev
    events:
      - s3:
          bucket: import-file-aws-node
          event: s3:ObjectCreated:*
          existing: true
